# Generated by Django 3.1.4 on 2020-12-03 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.PositiveIntegerField(default=5)),
                ('image', models.ImageField(upload_to='static/discount')),
            ],
        ),
        migrations.CreateModel(
            name='Sox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.TextField()),
                ('image', models.ImageField(upload_to='static/sox')),
                ('fabrics', models.TextField()),
                ('size', models.TextField()),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.discount')),
            ],
        ),
    ]
