# Generated by Django 3.1.4 on 2020-12-03 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Discount', 'verbose_name_plural': 'Discount'},
        ),
        migrations.AlterModelOptions(
            name='sox',
            options={'verbose_name': 'Sox', 'verbose_name_plural': 'Sox'},
        ),
        migrations.AlterField(
            model_name='sox',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.discount'),
        ),
    ]
